version: '3.8'
services:
  mongo:
    image: mongo:6
    container_name: eet-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: eet
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
